defaults: &defaults
  admin_emails:
    - "h.bing612@gmail.com"

development:
  <<: *defaults
  admin_emails:
    - "test1@test.com"

test:
  <<: *defaults
  admin_emails:
    - "admin@admin.com"

production:
  <<: *defaults
